'use strict';
function weightedScore(rows){let weight=0,total=0;for(const [score,credit] of rows){weight+=score*credit;total+=credit;}return {weight,total,score:weight/total};}
const yearSelect=document.getElementById('school-year');
for(let y=2020;y<=2040;y++){const o=new Option(`${y}—${y+1} 学年`,`${y}-${y+1}`);yearSelect.add(o);document.getElementById('import-year').add(o.cloneNode(true));}yearSelect.value='2024-2025';
function updateYear(){document.querySelectorAll('.card-head .small').forEach(el=>el.textContent=yearSelect.selectedOptions[0].textContent);}
yearSelect.onchange=updateYear;
window.semesterControls=[];
const semesterScores=[null,null];
function updateAnnualScore(){
 const ready=semesterScores.every(Number.isFinite);
 document.getElementById('annual-score').textContent=ready?((semesterScores[0]+semesterScores[1])/2).toFixed(2):'—';
 document.getElementById('annual-detail').textContent=ready?'两个学期各占 50%，使用未四舍五入的学期成绩计算，最终保留两位小数。':'请先完成两个学期的成绩计算。';
}
['第一学期','第二学期'].forEach((name,index)=>{
 const card=document.createElement('section');card.className='semester';card.setAttribute('aria-label',name);
 card.innerHTML=`<div class="card-head"><span class="badge">0${index+1}</span><div><h2>${name}</h2><div class="small">2024—2025 学年</div></div></div><form novalidate class="entry"><div class="rows"></div><button class="add" type="button">＋ 添加课程</button><p class="error" role="alert"></p><button class="calculate" type="submit">计算${name}智育成绩</button></form><div class="result" aria-live="polite"><div class="result-label">${name}智育成绩</div><div class="scoreline"><output class="score">—</output><span class="unit">分</span></div><div class="stats">录入课程后点击计算</div><div class="expression"></div></div>`;
 document.getElementById('semesters').append(card);const rows=card.querySelector('.rows'),error=card.querySelector('.error');
 function clearResult(){semesterScores[index]=null;updateAnnualScore();card.querySelector('.score').textContent='—';card.querySelector('.stats').textContent='录入或修改课程后点击计算';card.querySelector('.expression').textContent='';error.textContent='';}
 function relabel(){[...rows.children].forEach((row,i)=>{row.querySelector('.course-name').setAttribute('aria-label',`${name}第${i+1}门课程名称`);row.querySelector('.course-name').placeholder=`课程 ${i+1}（名称选填）`;row.querySelector('.remove').setAttribute('aria-label',`删除${name}第${i+1}门课程`);});}
 function add(values={},focus=false){const row=document.createElement('div');row.className='course-entry';row.innerHTML='<input class="course-name" type="text"><div class="row"><label>初考成绩<input class="grade" type="number" min="0" max="100" step="any" inputmode="decimal" placeholder="0—100" required></label><label>应得学分<input class="credit" type="number" min="0" step="any" inputmode="decimal" placeholder="如 2.5" required></label><button type="button" class="remove" title="删除课程">×</button></div>';rows.append(row);row.querySelector('.course-name').value=values.name||'';row.querySelector('.grade').value=values.score??'';row.querySelector('.credit').value=values.credit??'';row.querySelector('.remove').onclick=()=>{row.remove();relabel();clearResult();};row.querySelectorAll('input').forEach(input=>input.oninput=()=>{input.removeAttribute('aria-invalid');clearResult();});relabel();clearResult();if(focus)row.querySelector('.grade').focus();}
 function calculate(){clearResult();const values=[];let firstInvalid=null;const errors=[];[...rows.children].forEach((row,i)=>{const inputs=[row.querySelector('.grade'),row.querySelector('.credit')];inputs.forEach(input=>input.removeAttribute('aria-invalid'));const [s,c]=inputs.map(x=>x.valueAsNumber);const invalidS=!Number.isFinite(s)||s<0||s>100;const invalidC=!Number.isFinite(c)||c<=0;if(invalidS||invalidC){errors.push(`第${i+1}门课：${invalidS?'请填写 0—100 的初考成绩':''}${invalidS&&invalidC?'；':''}${invalidC?'请填写大于 0 的学分':''}`);inputs.forEach((input,j)=>{if(j?invalidC:invalidS){input.setAttribute('aria-invalid','true');firstInvalid??=input;}});}else values.push([s,c]);});if(!rows.children.length){error.textContent='请先添加至少一门课程。';return;}if(errors.length){error.textContent=errors.join('。');firstInvalid.focus();return;}const result=weightedScore(values);if(!Number.isFinite(result.weight)||!Number.isFinite(result.total)||!Number.isFinite(result.score)){error.textContent='学分数值过大，请检查后重新输入。';return;}semesterScores[index]=result.score;updateAnnualScore();const fmt=n=>Number(n.toFixed(6)).toString();card.querySelector('.score').textContent=result.score.toFixed(2);card.querySelector('.stats').textContent=`${values.length} 门课程 · 总学分 ${fmt(result.total)} · 加权总分 ${fmt(result.weight)}`;card.querySelector('.expression').textContent=`${fmt(result.weight)} ÷ ${fmt(result.total)} = ${result.score.toFixed(2)}`;}
 card.querySelector('.add').onclick=()=>add({},true);card.querySelector('form').onsubmit=e=>{e.preventDefault();calculate();};
 window.semesterControls.push({import(values,replace){if(replace)rows.replaceChildren();else [...rows.children].filter(r=>[...r.querySelectorAll('input')].every(i=>!i.value)).forEach(r=>r.remove());values.forEach(v=>add(v));calculate();card.scrollIntoView({behavior:'smooth',block:'start'});},hasData(){return [...rows.querySelectorAll('input')].some(i=>i.value!=='');}});
 for(let i=0;i<3;i++)add();
});
