'use strict';
(()=>{
const $=id=>document.getElementById(id),fileInput=$('image-file'),status=$('ocr-status'),review=$('review'),reviewRows=$('review-rows');let worker=null,run=0,previewURL=null;
fileInput.closest('label').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!fileInput.disabled)fileInput.click();}};
function loadOCR(){if(window.Tesseract)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='vendor/ocr/tesseract.min.js';script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('识别组件加载失败，请检查网络后重试。'));};document.head.append(script);});}
function canvas(w,h){const c=document.createElement('canvas');c.width=Math.round(w);c.height=Math.round(h);return c;}
function prepare(img){const scale=Math.min(2,4400/img.naturalWidth,4400/img.naturalHeight,Math.sqrt(9000000/(img.naturalWidth*img.naturalHeight)));const c=canvas(img.naturalWidth*scale,img.naturalHeight*scale),ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const pixels=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<pixels.data.length;i+=4){const d=pixels.data,v=d[i]<155&&d[i+1]<155&&d[i+2]<155?0:255;d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(pixels,0,0);return c;}
function cropColumn(original,processed,layout,key){const col=layout[key],zoom=key==='score'?2:1,c=canvas((col.right-col.left)*zoom,(layout.bottom-layout.top)*zoom),ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);if(key==='score'){const sx=original.naturalWidth/processed.width,sy=original.naturalHeight/processed.height;ctx.imageSmoothingQuality='high';ctx.drawImage(original,col.left*sx,layout.top*sy,(col.right-col.left)*sx,(layout.bottom-layout.top)*sy,0,0,c.width,c.height);const p=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<p.data.length;i+=4){const d=p.data,v=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2]<180?0:255;d[i]=d[i+1]=d[i+2]=v;}ctx.putImageData(p,0,0);}else ctx.drawImage(processed,col.left,layout.top,col.right-col.left,layout.bottom-layout.top,0,0,c.width,c.height);return c;}
function addReview(data={}){const row=document.createElement('div');row.className='review-row';row.innerHTML='<label>课程名称（可修改）<input type="text" class="r-name"></label><label>分数<input type="number" class="r-score" min="0" max="100" step="any" required inputmode="decimal"></label><label>学分<input type="number" class="r-credit" min="0" step="any" required inputmode="decimal"></label><button class="remove" type="button" aria-label="删除此识别课程">×</button>';row.querySelector('.r-name').value=data.name||'';row.querySelector('.r-score').value=data.score??'';row.querySelector('.r-credit').value=data.credit??'';row.querySelector('.remove').onclick=()=>{row.remove();$('confirm-import').checked=false;};row.oninput=()=>{$('confirm-import').checked=false;};reviewRows.append(row);}
$('add-review').onclick=()=>addReview();$('source-image').onclick=()=>{$('source-image').classList.toggle('expanded');};
function setBusy(b){fileInput.disabled=b;fileInput.closest('label').classList.toggle('busy',b);$('cancel-ocr').hidden=!b;}
$('cancel-ocr').onclick=()=>{run++;if(worker){worker.terminate();worker=null;}status.textContent='已取消识别，可以重新选择图片。';setBusy(false);};
fileInput.onchange=async()=>{const file=fileInput.files[0];fileInput.value='';if(!file)return;const current=++run;review.hidden=true;$('review-error').textContent='';$('confirm-import').checked=false;reviewRows.replaceChildren();if(!/^image\/(png|jpeg|webp|bmp)$/.test(file.type)){status.textContent='请选择 PNG、JPG、WEBP 或 BMP 图片。';return;}if(file.size>15*1024*1024){status.textContent='图片超过 15MB，请压缩后重新选择。';return;}setBusy(true);status.textContent='正在准备识别，首次加载可能需要几十秒…';let localWorker=null;
try{if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);const img=$('source-image');img.src=previewURL;await img.decode();if(img.naturalWidth*img.naturalHeight>24000000)throw Error('图片尺寸过大，请裁剪成绩表区域后重试。');$('image-preview').hidden=false;img.classList.remove('expanded');const processed=prepare(img);await loadOCR();if(current!==run)return;localWorker=await Tesseract.createWorker('chi_sim',1,{workerPath:new URL('vendor/ocr/worker.min.js',location.href).href,corePath:new URL('vendor/ocr/core',location.href).href,langPath:new URL('vendor/ocr/lang',location.href).href,workerBlobURL:false,cacheMethod:'none'});if(current!==run){await localWorker.terminate();return;}worker=localWorker;let recognized=null;
const grid=TableOCR.detect(img);
if(grid)recognized=await TableOCR.recognize(worker,img,grid,text=>{if(current===run)status.textContent=text;},()=>current===run);
if(current!==run)return;
if(!recognized){
await worker.reinitialize('chi_sim',1);
await worker.setParameters({tessedit_pageseg_mode:'6',user_defined_dpi:'150'});status.textContent='正在定位课程、学分和成绩列…';
const first=await worker.recognize(processed,{}, {text:true,blocks:true});if(current!==run)return;
const layout=ScoreOCR.layout(first.data,processed.width,processed.height);
await worker.reinitialize('eng',1);await worker.setParameters({tessedit_pageseg_mode:'6',user_defined_dpi:'150'});
const scores=await worker.recognize(cropColumn(img,processed,layout,'score'),{}, {text:true,blocks:true});if(current!==run)return;
const credits=await worker.recognize(cropColumn(img,processed,layout,'credit'),{}, {text:true,blocks:true});if(current!==run)return;
recognized={layout,sv:ScoreOCR.numericRows(scores.data,layout.top,layout.rows,100,2),cv:ScoreOCR.numericRows(credits.data,layout.top,layout.rows,999)};
}
const {layout,sv,cv}=recognized;
layout.rows.forEach((r,i)=>addReview({name:r.name,score:sv[i],credit:cv[i]}));$('import-year').value=layout.year||yearSelect.value;if(!$('import-year').value)$('import-year').value=yearSelect.value;$('import-semester').value=layout.semester??0;$('import-mode').value='append';$('recognized-info').textContent=`已读取“${layout.score.label}”列。课程名称可能有错字；分数、学分和课程数量均需对照原图核对。${layout.semester===null?'未能确定学期，请手动选择。':''}`;review.hidden=false;status.textContent=`已识别 ${layout.rows.length} 门课程。${sv.filter(v=>v==='').length+cv.filter(v=>v==='').length?'有数值未识别，请补全空白项。':'请核对后确认导入。'}`;
}catch(e){if(current===run)status.textContent=e.message||'图片识别失败，请换一张清晰的完整成绩单截图重试。';}finally{if(localWorker)await localWorker.terminate().catch(()=>{});if(current===run){worker=null;setBusy(false);}}};
review.onsubmit=e=>{e.preventDefault();$('review-error').textContent='';const items=[...reviewRows.children].map(row=>({name:row.querySelector('.r-name').value,score:row.querySelector('.r-score').value,credit:row.querySelector('.r-credit').value}));if(!items.length){$('review-error').textContent='请至少保留一门课程。';return;}if(items.some(i=>i.score===''||i.credit===''||!Number.isFinite(+i.score)||!Number.isFinite(+i.credit)||+i.score<0||+i.score>100||+i.credit<=0)){ $('review-error').textContent='请补全所有分数与学分：分数为 0—100，学分大于 0。';return;}if(!$('confirm-import').checked){$('review-error').textContent='请先核对并勾选确认。';return;}const target=Number($('import-semester').value),year=$('import-year').value;if(year!==yearSelect.value&&semesterControls.some(s=>s.hasData())){if(!window.confirm('切换学年会同时更改两个学期的学年标签，现有课程仍会保留。请确认现有课程属于该学年。'))return;}if($('import-mode').value==='replace'&&semesterControls[target].hasData()&&!window.confirm('确认替换所选学期的全部课程？此操作会移除该学期原有录入。'))return;yearSelect.value=year;updateYear();semesterControls[target].import(items,$('import-mode').value==='replace');review.hidden=true;status.textContent=`已导入 ${items.length} 门课程到${year} 学年第${target+1}学期，并完成计算。`;};
})();
